baseURL = "https://upodcast.ru/"

languagecode = "ru-RU"
defaultContentLanguage = "ru"
title = "UPodcast"
theme = "axiom"

[taxonomies]
category = "categories"

paginate = 2
canonifyURLs = true
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[params]
mainSections = ["blog"]
copyrightYear = 2010
dateFormat = "2 Jan 2006 "
highlight = "dark"

[params.logo]
inline = true
path = "upodcastLogo.svg"

[params.image]
faviconIco = "favicon.ico"
faviconAlt = "favicon-32x32.png"
icon1To1 = "favicon192.png"
icon2To1 = "favicon384.png"


[params.social]
github = "https://github.com/upodcast"
twitter = "https://twitter.com/u_podcast"
facebook = "https://facebook.com/upodcast"

footer = ["twitter", "github", "facebook"]

[params.services]
analyticsId = "UA-171096637-1"

[menu]
[[menu.main]]
url = "/episode/"
name = "Выпуски"
weight = 1

[[menu.main]]
url = "/blog/"
name = "Блог"
weight = 2


[[menu.foot]]
url = "/episode/"
name = "Выпуски"
weight = 1

[[menu.foot]]
url = "/afterparty/"
name = "ПослеШоу"
weight = 2

[[menu.foot]]
url = "/review/"
name = "Rev.u"
weight = 3

[[menu.foot]]
url = "/uidea/"
name = "U.Idea"
weight = 4

[[menu.foot]]
url = "/blog/"
name = "Блог"
weight = 5

[languages]
[languages."ru"]
weight = 1
languageName = "Русский"

[outputs]
home = ["HTML", "ATOM", "RSS"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false
